# Generated by Django 5.1.3 on 2024-11-09 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Apple', max_length=50, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('english_title', models.CharField(default='Apple', max_length=50, verbose_name='english title')),
                ('image', models.ImageField(upload_to='brand', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Barnd',
                'verbose_name_plural': 'Barnds',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30, verbose_name='color_name')),
                ('color_code', models.CharField(max_length=30, verbose_name='color_code')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.customer', verbose_name='customer')),
                ('province', models.CharField(max_length=255, verbose_name='province')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('postal_code', models.CharField(max_length=50, verbose_name='postal_code')),
            ],
            options={
                'verbose_name': 'Addresse',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('english_title', models.CharField(blank=True, max_length=255, verbose_name='english title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='image')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='cover')),
                ('is_parent', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_parent')),
                ('is_offer', models.BooleanField(blank=True, default=False, null=True, verbose_name='is offer')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='store.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='product')),
                ('english_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='english title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveBigIntegerField(verbose_name='price')),
                ('old_price', models.PositiveBigIntegerField(verbose_name='old_price')),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10, verbose_name='status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.brand', verbose_name='brand')),
                ('category', models.ManyToManyField(related_name='products', to='store.category', verbose_name='category')),
                ('color', models.ManyToManyField(related_name='products', to='store.color', verbose_name='color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product-image', verbose_name='images')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
            },
        ),
    ]
