# Generated by Django 5.1.3 on 2024-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=10, verbose_name='status'),
        ),
    ]
