# Generated by Django 5.1.2 on 2024-11-07 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_phone_number_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='request_id')),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=5, verbose_name='channel')),
                ('receiver', models.CharField(max_length=20, verbose_name='receiver')),
                ('password', models.CharField(max_length=8, verbose_name='password')),
                ('datetima_created', models.DateTimeField(editable=False, verbose_name='datetima_created')),
            ],
        ),
    ]
