# Generated by Django 5.1.2 on 2024-11-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
